models:
  board_detector:
    path: './models/board_detector.pt'
  bet_detector:
    path: './models/bet_detector.pt'
  player-pot_detector:
    path: './models/pot_detector.pt'
  accepted_pot_detector:
    path: './models/accepted_pot_detector.pt'
  non_accepted_pot_detector:
    path: './models/non_accepted_pot_detector.pt'
  card_detector:
    path: './models/card_detector.pt'

server:
  url: '103.90.73.217'
  redis_port: '6379'

logging:
  level: 'INFO'
  path: '/var/log/poker_analyzer'

board:
  players: 6
